channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=23.1.2
- pip:
  - mlflow==2.14.3
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - scipy==1.13.1
  - statsmodels==0.14.2
name: mlflow-env